### ISSUE TITLE
TweakScale cannot check the presens of TweakScaleCompanion

### ISSUE THREAD

**Issue by handw3rker** [TweakScale/TweakScale#318] opened 2023-11-16 20:58 UTC
Small error while loading TweakScale in KSP.log:

`[LOG 07:55:24.364] [TweakScale] ERROR: Could not check the presense of TweakScale Companion due Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\TweakScaleCompanion" at error:0`

I'm not familiar with C# programming (but other languages). So as I can see the following line is the problem:
 https://github.com/TweakScale/TweakScale/blob/a5fa015e511da9dabb93a14d9fc647122d9a410b/Source/Scale/CompanionSupport.cs#L125

In the function call `LoadVersion()` there must be the second param `vendor` (as null) to match the overloaded function
`public static Version LoadVersion(string addonName, string vendor = null)`
 in KSPe. Without there will be no path solving. That's explains the wrong folder in the error message.

The line should look like
`KSPe.Util.AddOnVersionChecker.Version v = KSPe.Util.AddOnVersionChecker.LoadVersion("TweakScaleCompanion", null);`

Am I correct with this?

Thanks a lot for your effort in development of these great tool(s)! 

Greetz,
Thomas

**Comment by Lisias** [comment] 2023-11-16 22:39
Hi, @handw3rker !

Gee! You are right!! O screwed up when I created a new helper on KSPe! Fixing it!

**Comment by Lisias** [comment] 2023-11-16 22:44
Better, there's nothing to be fixed on TweakScale, the problem is on KSPe:

https://github.com/net-lisias-ksp/KSPe/issues/63

So I'm closing this one, and will fix the mess where it's messed.

**Closed by Lisias** 2023-11-16 22:44 UTC
Labels: bug
